name: OSS Review Toolkit CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


env:
  SDK_VERSION: '9.0.102'
  TEST_RESULTS_DIRECTORY: './TestResults'
  POLICY_FILE: .github/oss-review-toolkit-policy.yml

jobs:
  oss-review:
    name: Run OSS Review Toolkit
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v4.2.2
      with:
        fetch-depth: 0

    - name: "Setup .NET"
      uses: actions/setup-dotnet@v4.2.0
      with:
        dotnet-version: ${{ env.SDK_VERSION }}

    - name: "Set up JDK"
      uses: actions/setup-java@v4.6.0
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Download and Extract ORT
      run: |
        curl -L -o ort.tgz https://github.com/oss-review-toolkit/ort/releases/download/46.0.0/ort-46.0.0.tgz
        mkdir -p ort
        tar -xzf ort.tgz -C ort
        chmod +x ort/ort

    - name: Run OSS Review Toolkit Analyzer with Policy
      env:
        REPO_PATH: ${{ github.workspace }}
      run: |
        ./ort/ort analyze \
          -i . \
          -o ort-results \
          --package-managers NuGet \
          --rules-file ${{ github.workspace }}/${{ env.POLICY_FILE }}

    - name: Generate ORT Report
      run: |
        ./ort/ort report \
          -i ort-results \
          -o ort-report

    - name: Upload ORT Report Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: oss-review-report
        path: ort-report

    - name: Fail on ORT issues
      run: |
        if grep -q "ERROR" ort-results/*.log; then
          echo "ORT found license issues!"
          exit 1
        fi
